### ISSUE TITLE
Datasets with a lot of features

### ISSUE THREAD

**Issue by michaelshekasta** [idanmoradarthas/DataScienceUtils#15]
Hi,

Thanks for great utilities. It will great if you can take care of about 2 things:
1. datasets with lot of features - as I saw, many datasets contains 100 features or more. You can't explore anything when you run visualize_features on them.
2. dependency graphs - can you please create a function that show the dependency between feature value and target?

Regards,
Michael

**Comment by idanmoradarthas** [comment]
Hi thanks for the feedback =)
1. I can fix this in two ways: First, add several parameters such as: number of columns, list of feature to display and more. Second, adjust the function to return an HTML instead of matplotlib's figure, what will enable scrolling. The second solution will be too much similar to pandas profiling which I'm trying to avoid, so I think I'll go with option number one.
2. Do you mean partial regression plot? If so, you can use pdpbox package to do so. See https://github.com/SauceCat/PDPbox or you see my kaggle notebook https://www.kaggle.com/idanmorad/exercise-shap-values see step 2.

Have fun coding,
Idan

**Comment by idanmoradarthas** [comment]
added parameters: features: list of feature to visualize, 
num_columns: number of columns in the grid, and remove_na: True to ignore NA values when plotting; False otherwise.
in https://github.com/idanmoradarthas/DataScienceUtils/pull/17
see CHANGELOG.md
